name: Deploy docs

on:
  push:
    branches:
      - master
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen 
    - name: Build Documentation
      run: |
        cd doc
        doxygen
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: contains(github.ref,'refs/heads/master')
      with:
        branch: gh-pages
        folder: doc/html
        clean: false